email_provider_domains = {
    'activegate-ss.jp': 'Activegate SS',
    'antispameurope.com': 'hornetsecurity',
    'appriver.com': 'AppRiver',
    'arsmtp.com': 'AppRiver',
    'avgcloud.net': 'AVG',
    'baesystems.com': 'BAE Systems',
    'barracuda.de': 'Barracuda',
    'barracuda.net': 'Barracuda',
    'barracudamoto.co.uk': 'Barracuda',
    'barracudanetworks.com': 'Barracuda',
    'borderware.com': 'Watchguard',
    'canit.ca': 'Can-It Pro',
    'clearswift.com':'Clearswift',
    'ctmail.com': 'Cyren',
    'deteque.com': 'Deteque',
    'everycloudtech.com': 'hornetsecurity',
    'everycloudtech.us': 'hornetsecurity',
    'exchangedefender.com': 'Exchange Defender',
    'fireeyecloud.com': 'FireEye',
    'fireeyegov.com': 'FireEye',
    'fortimail.com': 'Fortinet',
    'frontbridge.com': 'Microsoft Frontbridge',
    'fusemail.net': 'fusemail',
    'futurespam.com': 'hornetsecurity',
    'ibarracuda.nl': 'iBarracuda',
    'ik2.com': 'MXGuarddog',
    'ik2.eu': 'MXGuarddog',
    'iphmx.com': 'Cisco Ironport',
    'kaspersky-labs.com': 'Kaspersky',
    'mailanyone.net': 'Protonmail',
    'mailchannels.net': 'mailchannels',
    'mailcontrol.com': 'Forcepoint',
    'mailhop.co': 'DuoCircle',
    'mailhop.co.uk': 'DuoCircle',
    'mailhop.org': 'DuoCircle',
    'mailhop.us': 'DuoCircle',
    'mbox.net': 'BAE Systems',
    'mcafee.com': 'Mcafee',
    'messagelabs.com': 'Symmantec',
    'mimecast-offshore.com': 'Mimecast',
    'mimecast.co.za': 'Mimecast',
    'mimecast.com': 'Mimecast',
    'mpmailmx.com': 'hornetsecurity',
    'mpmailmx.com': 'Manage Protect',
    'mpmailmx.net': 'hornetsecurity',
    'mx-relay.com': 'MX Relay',
    'mxlogic.net': 'Mcafee',
    # not really a security provider
#     'mxproc.com': 'bounce.io / betterbounces',
#     'h-email.net':'bounce.io / betterbounces', 
#     'b-io.co': 'bounce.io / betterbounces',
    'mxrecord.io': 'Area1',
    'mxsmtp.com': 'Trustwave',
    'mxthunder.com': 'SpamHero',
    'mxthunder.net': 'SpamHero',
    'pandasecurity.com': 'Panda Security',
    'perimeterusa.com': 'BAE Systems',
    'postoffice.net': 'BAE Systems',
    'ppe-hosted.com': 'Proofpoint',
    'pphosted.com': 'Proofpoint',
    'protonmail.ch': 'Protonmail',
    'rcimx.com': 'EdgeWave',
    'rcimx.net': 'EdgeWave',
    'rcimx.net': 'Edgewave',
    'reflexion.net': 'Reflexion',
    'retarus.com': 'Retarus',
    'rmx.de': 'Retarus',
    'securemx.jp': 'SecureMX',
    'securence.com': 'Securence.com',
    'sendio.com': 'Sendio',
    'snwlhosted.com': 'Sonic Wall',
    'snwlhostedeu.com': 'Sonic Wall',
    'sonicwall.com': 'Sonic Wall',
    'sophos.com': 'Sophos',
    'spamexperts.com': 'Solarwinds',
    'antispamcloud.com': 'Solarwinds',
    'spamhero.com': 'SpamHero',
    'spamhero.net': 'SpamHero',
    'spamina.com': 'hornetsecurity',
    'spamtitan.com': 'SpamTitan',
    'symantec.com': 'Symantec',
    'theemaillaundry.net': 'the email laundry',
    'trendmicro.com': 'Trend Micro',
    'trendmicro.eu': 'Trend Micro',
    'trendmicro.tw': 'Trend Micro',
    'trustwave.com': 'Trustwave',
    'ual.com': 'BAE Systems',
    'usa.net': 'BAE Systems',
    'vadesecure.com': 'vadesecure',
    'watchguard.com': 'Watchguard',
    'zixmail.net': 'ZixMail',
    'zixsmbhosted.com': 'ZixMail',
    'psmtp.com': 'Postini',
    'mailinblack.com': 'Mail in Black',
    'scanscope.net': 'Censornet',
    'emailservice.io': 'Mailprotector',
}

email_provider_asns = {
    'AppRiver AG': 'AppRiver',
    'APPRIVER LLC': 'AppRiver',
    'AS-APPRIVER': 'AppRiver',
    'AS-CISCOHPS-APAC': 'Cisco Ironport',
    'AS-IRONP-VEGA': 'Cisco Ironport',
    'AS-TRENDMICRO-COM': 'Trend Micro',
    'AS2-TRENDMICRO-COM': 'Trend Micro',
    'ASN-REFLEXION': 'Reflexion',
    'BAE Systems Applied Intelligence US Corp.': 'BAE Systems',
    'BAE Systems Inc.': 'BAE Systems',
    'BAE-NET-ASN': 'BAE Systems',
    'Barracuda Networks, Inc.': 'Barracuda',
    'BARRACUDA-NETWORKS-INC': 'Barracuda',
    'Cisco Systems Ironport Division': 'Cisco Ironport',
    'Cisco Systems, Inc.': 'Cisco Ironport',
    'CISCOSYSTEMS': 'Cisco Ironport',
    'CSC-IGN-EMEA': 'BAE Systems', 
    'Edgewave, Inc.': 'Edgewave',
    'FireEye, Inc.': 'FireEye',
    'Forcepoint Cloud Ltd': 'Forcepoint',
    'Fortinet Inc.': 'Fortinet',
    'FORTINET': 'Fortinet',
    'HKN GmbH': 'hornetsecurity',
    'IRONPORT-SYSTEMS-INC': 'Cisco Ironport',
    'Kaspersky Lab AO': 'Kaspersky',
    'MCAFEE': 'Mcafee',
    'McAfee, Inc.': 'Mcafee',
    'MessageLabs Inc.': 'Symmantec',
    'Messagelabs Limited': 'Symmantec',
    'Messagelabs-AS': 'Symmantec',
    'Mimecast Australia Pty Ltd': 'Mimecast',
    'Mimecast North America Inc': 'Mimecast',
    'Mimecast Services Limited': 'Mimecast',
    'MIMECAST': 'Mimecast',
    'MimecastSA': 'Mimecast',
    'MX Logic, Inc.': 'Mcafee',
    'PERIMETER-ESECURITY': 'BAE Systems',
    'Proofpoint, Inc.': 'Proofpoint',
    'PROOFPOINT-ASN-US-EAST': 'Proofpoint',
    'PROOFPOINT-ASN-US-WEST': 'Proofpoint',
    'PROOFPOINT-UT7': 'Proofpoint',
    'Proton Technologies AG': 'Protonmail',
    'Reflexion Networks, Inc.': 'Reflexion',
    'retarus GmbH': 'Retarus',
    'SNWL-COLO-SJL': 'Sonic Wall',
    'SonicWALL, Inc.': 'Sonic Wall',
    'Symantec Corporation': 'Symantec',
    'SYMANTEC': 'Symantec',
    'SYMANTEC-CORPORATION': 'Symantec',
    'TREND MICRO INCORPORATED': 'Trend Micro',
    'Trustwave Holdings, Inc.': 'Trustwave',
    'TRUSTWAVE-ASN': 'Trustwave',
    'WatchGuard Technologies, Inc.': 'Watchguard',
    'WATCHGUARD-TECHNOLOGIES-INC': 'Watchguard',
    'Zix Corporation': 'ZixMail',
    'ZIXI': 'ZixMail',
    'DETEQUE': 'Deteque',
}